version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:stable
    depends_on:
      - api
      - frontend-nuxt
      - frontend-vue
      - mysql
    networks:
      - internal
    volumes:
      - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - internal
    ports:
      - 3307:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=boilerplate
      - TZ=Australia/Melbourne

  migration:
    container_name: migration
    image: $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:api-dev
    depends_on:
      - mysql
    networks:
      - internal
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=boilerplate
      - DB_CONNECTION_LIMIT=10
      - DB_DEBUG=true
      - TZ=Australia/Melbourne
    command:
      - /usr/local/bin/migration.sh

  api:
    container_name: api
    image: $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:api-dev
    depends_on:
      - mysql
      - migration
    networks:
      - internal
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=boilerplate
      - DB_CONNECTION_LIMIT=10
      - DB_DEBUG=true
      - JWT_SECRET_KEY=vsKpsTgstlhmg8yIA82d
      - JWT_EXPIRES_IN=1w
      - BCRYPT_SALTING_ROUND=10
      - API_URL=http://api:3000
      - BACKEND_URL=http://backend:8080
      - FRONTEND_URL=http://frontend:8080
      - EMAIL_FROM_ADDRESS=support@$SERVICE_DOMAIN
      - EMAIL_FROM_NAME=Support
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_SECURE=false
      - SMTP_AUTH_USER=
      - SMTP_AUTH_PASS=
      - SMTP_DEBUG=true
      - SMTP_LOGGER=true
      - TZ=Australia/Melbourne

  frontend-nuxt:
    container_name: frontend-nuxt
    image: $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:frontend-nuxt-dev
    depends_on:
      - mysql
    networks:
      - internal
    environment:
      - API_URL=http://api:3000
      - FORMAT_DATETIME="YYYY-MM-DD HH:MM:SS"
    command: npm run dev

  frontend-vue:
    container_name: frontend-vue
    image: $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:frontend-vue-dev
    depends_on:
      - mysql
    networks:
      - internal
    environment:
      - API_URL=http://api:3000
    command: npm run serve

  backend:
    container_name: backend
    image: $REGISTRY_DOMAIN/chrisleekr/nodejs-vuejs-mysql-boilerplate:backend-dev
    depends_on:
      - mysql
    networks:
      - internal
    environment:
      - API_URL=http://api:3000
    command: npm run serve


  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  mysql_data:
